# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `activestorage-validator` gem.
# Please instead update this file by running `bin/tapioca gem activestorage-validator`.


# source://activestorage-validator//lib/activestorage/validator/blob.rb#1
module ActiveRecord
  class << self
    # source://activerecord/8.0.1/lib/active_record.rb#361
    def action_on_strict_loading_violation; end

    # source://activerecord/8.0.1/lib/active_record.rb#361
    def action_on_strict_loading_violation=(_arg0); end

    # source://activerecord/8.0.1/lib/active_record.rb#527
    def after_all_transactions_commit(&block); end

    # source://activerecord/8.0.1/lib/active_record.rb#547
    def all_open_transactions; end

    # source://activerecord/8.0.1/lib/active_record.rb#354
    def application_record_class; end

    # source://activerecord/8.0.1/lib/active_record.rb#354
    def application_record_class=(_arg0); end

    # source://activerecord/8.0.1/lib/active_record.rb#283
    def async_query_executor; end

    # source://activerecord/8.0.1/lib/active_record.rb#283
    def async_query_executor=(_arg0); end

    # source://activerecord/8.0.1/lib/active_record.rb#348
    def before_committed_on_all_records; end

    # source://activerecord/8.0.1/lib/active_record.rb#348
    def before_committed_on_all_records=(_arg0); end

    # source://activerecord/8.0.1/lib/active_record.rb#345
    def belongs_to_required_validates_foreign_key; end

    # source://activerecord/8.0.1/lib/active_record.rb#345
    def belongs_to_required_validates_foreign_key=(_arg0); end

    # source://activerecord/8.0.1/lib/active_record.rb#211
    def database_cli; end

    # source://activerecord/8.0.1/lib/active_record.rb#211
    def database_cli=(_arg0); end

    # source://activerecord/8.0.1/lib/active_record.rb#233
    def db_warnings_action; end

    # source://activerecord/8.0.1/lib/active_record.rb#235
    def db_warnings_action=(action); end

    # source://activerecord/8.0.1/lib/active_record.rb#262
    def db_warnings_ignore; end

    # source://activerecord/8.0.1/lib/active_record.rb#262
    def db_warnings_ignore=(_arg0); end

    # source://activerecord/8.0.1/lib/active_record.rb#214
    def default_timezone; end

    # source://activerecord/8.0.1/lib/active_record.rb#218
    def default_timezone=(default_timezone); end

    # source://activerecord/8.0.1/lib/active_record/deprecator.rb#4
    def deprecator; end

    # source://activerecord/8.0.1/lib/active_record.rb#182
    def disable_prepared_statements; end

    # source://activerecord/8.0.1/lib/active_record.rb#182
    def disable_prepared_statements=(_arg0); end

    # source://activerecord/8.0.1/lib/active_record.rb#510
    def disconnect_all!; end

    # source://activerecord/8.0.1/lib/active_record.rb#409
    def dump_schema_after_migration; end

    # source://activerecord/8.0.1/lib/active_record.rb#409
    def dump_schema_after_migration=(_arg0); end

    # source://activerecord/8.0.1/lib/active_record.rb#419
    def dump_schemas; end

    # source://activerecord/8.0.1/lib/active_record.rb#419
    def dump_schemas=(_arg0); end

    # source://activerecord/8.0.1/lib/active_record.rb#499
    def eager_load!; end

    # source://activerecord/8.0.1/lib/active_record.rb#380
    def error_on_ignored_order; end

    # source://activerecord/8.0.1/lib/active_record.rb#380
    def error_on_ignored_order=(_arg0); end

    # source://activerecord/8.0.1/lib/active_record/gem_version.rb#5
    def gem_version; end

    # source://activerecord/8.0.1/lib/active_record.rb#460
    def generate_secure_token_on; end

    # source://activerecord/8.0.1/lib/active_record.rb#460
    def generate_secure_token_on=(_arg0); end

    # source://activerecord/8.0.1/lib/active_record.rb#306
    def global_executor_concurrency; end

    # source://activerecord/8.0.1/lib/active_record.rb#298
    def global_executor_concurrency=(global_executor_concurrency); end

    # source://activerecord/8.0.1/lib/active_record.rb#286
    def global_thread_pool_async_query_executor; end

    # source://activerecord/8.0.1/lib/active_record.rb#321
    def index_nested_attribute_errors; end

    # source://activerecord/8.0.1/lib/active_record.rb#321
    def index_nested_attribute_errors=(_arg0); end

    # source://activerecord/8.0.1/lib/active_record.rb#189
    def lazily_load_schema_cache; end

    # source://activerecord/8.0.1/lib/active_record.rb#189
    def lazily_load_schema_cache=(_arg0); end

    # source://activerecord/8.0.1/lib/active_record.rb#339
    def maintain_test_schema; end

    # source://activerecord/8.0.1/lib/active_record.rb#339
    def maintain_test_schema=(_arg0); end

    # source://activerecord/8.0.1/lib/active_record.rb#463
    def marshalling_format_version; end

    # source://activerecord/8.0.1/lib/active_record.rb#467
    def marshalling_format_version=(value); end

    # source://activerecord/8.0.1/lib/active_record.rb#400
    def migration_strategy; end

    # source://activerecord/8.0.1/lib/active_record.rb#400
    def migration_strategy=(_arg0); end

    # source://activerecord/8.0.1/lib/active_record.rb#311
    def permanent_connection_checkout; end

    # source://activerecord/8.0.1/lib/active_record.rb#314
    def permanent_connection_checkout=(value); end

    # source://activerecord/8.0.1/lib/active_record.rb#490
    def protocol_adapters; end

    # source://activerecord/8.0.1/lib/active_record.rb#490
    def protocol_adapters=(_arg0); end

    # source://activerecord/8.0.1/lib/active_record.rb#431
    def query_transformers; end

    # source://activerecord/8.0.1/lib/active_record.rb#431
    def query_transformers=(_arg0); end

    # source://activerecord/8.0.1/lib/active_record.rb#336
    def queues; end

    # source://activerecord/8.0.1/lib/active_record.rb#336
    def queues=(_arg0); end

    # source://activerecord/8.0.1/lib/active_record.rb#446
    def raise_int_wider_than_64bit; end

    # source://activerecord/8.0.1/lib/active_record.rb#446
    def raise_int_wider_than_64bit=(_arg0); end

    # source://activerecord/8.0.1/lib/active_record.rb#342
    def raise_on_assign_to_attr_readonly; end

    # source://activerecord/8.0.1/lib/active_record.rb#342
    def raise_on_assign_to_attr_readonly=(_arg0); end

    # source://activerecord/8.0.1/lib/active_record.rb#268
    def reading_role; end

    # source://activerecord/8.0.1/lib/active_record.rb#268
    def reading_role=(_arg0); end

    # source://activerecord/8.0.1/lib/active_record.rb#351
    def run_after_transaction_callbacks_in_order_defined; end

    # source://activerecord/8.0.1/lib/active_record.rb#351
    def run_after_transaction_callbacks_in_order_defined=(_arg0); end

    # source://activerecord/8.0.1/lib/active_record.rb#205
    def schema_cache_ignored_table?(table_name); end

    # source://activerecord/8.0.1/lib/active_record.rb#197
    def schema_cache_ignored_tables; end

    # source://activerecord/8.0.1/lib/active_record.rb#197
    def schema_cache_ignored_tables=(_arg0); end

    # source://activerecord/8.0.1/lib/active_record.rb#372
    def schema_format; end

    # source://activerecord/8.0.1/lib/active_record.rb#372
    def schema_format=(_arg0); end

    # source://activerecord/8.0.1/lib/active_record.rb#386
    def timestamped_migrations; end

    # source://activerecord/8.0.1/lib/active_record.rb#386
    def timestamped_migrations=(_arg0); end

    # source://activerecord/8.0.1/lib/active_record.rb#438
    def use_yaml_unsafe_load; end

    # source://activerecord/8.0.1/lib/active_record.rb#438
    def use_yaml_unsafe_load=(_arg0); end

    # source://activerecord/8.0.1/lib/active_record.rb#394
    def validate_migration_timestamps; end

    # source://activerecord/8.0.1/lib/active_record.rb#394
    def validate_migration_timestamps=(_arg0); end

    # source://activerecord/8.0.1/lib/active_record.rb#329
    def verbose_query_logs; end

    # source://activerecord/8.0.1/lib/active_record.rb#329
    def verbose_query_logs=(_arg0); end

    # source://activerecord/8.0.1/lib/active_record.rb#428
    def verify_foreign_keys_for_fixtures; end

    # source://activerecord/8.0.1/lib/active_record.rb#428
    def verify_foreign_keys_for_fixtures=(_arg0); end

    # source://activerecord/8.0.1/lib/active_record/version.rb#7
    def version; end

    # source://activerecord/8.0.1/lib/active_record.rb#265
    def writing_role; end

    # source://activerecord/8.0.1/lib/active_record.rb#265
    def writing_role=(_arg0); end

    # source://activerecord/8.0.1/lib/active_record.rb#453
    def yaml_column_permitted_classes; end

    # source://activerecord/8.0.1/lib/active_record.rb#453
    def yaml_column_permitted_classes=(_arg0); end
  end
end

# source://activestorage-validator//lib/activestorage/validator/blob.rb#2
module ActiveRecord::Validations
  mixes_in_class_methods ::ActiveRecord::Validations::ClassMethods

  # source://activerecord/8.0.1/lib/active_record/validations.rb#77
  def custom_validation_context?; end

  # source://activerecord/8.0.1/lib/active_record/validations.rb#47
  def save(**options); end

  # source://activerecord/8.0.1/lib/active_record/validations.rb#53
  def save!(**options); end

  # source://activerecord/8.0.1/lib/active_record/validations.rb#69
  def valid?(context = T.unsafe(nil)); end

  # source://activerecord/8.0.1/lib/active_record/validations.rb#69
  def validate(context = T.unsafe(nil)); end

  private

  # source://activerecord/8.0.1/lib/active_record/validations.rb#82
  def default_validation_context; end

  # source://activerecord/8.0.1/lib/active_record/validations.rb#90
  def perform_validations(options = T.unsafe(nil)); end

  # source://activerecord/8.0.1/lib/active_record/validations.rb#86
  def raise_validation_error; end
end

# source://activestorage-validator//lib/activestorage/validator/blob.rb#3
class ActiveRecord::Validations::BlobValidator < ::ActiveModel::EachValidator
  # source://activestorage-validator//lib/activestorage/validator/blob.rb#4
  def validate_each(record, attribute, values); end

  private

  # @return [Boolean]
  #
  # source://activestorage-validator//lib/activestorage/validator/blob.rb#24
  def valid_content_type?(blob); end
end

# source://activestorage-validator//lib/activestorage/validator/version.rb#1
module ActiveStorage
  # source://activestorage/8.0.1/lib/active_storage.rb#55
  def analyzers; end

  # source://activestorage/8.0.1/lib/active_storage.rb#55
  def analyzers=(val); end

  # source://activestorage/8.0.1/lib/active_storage.rb#61
  def binary_content_type; end

  # source://activestorage/8.0.1/lib/active_storage.rb#61
  def binary_content_type=(val); end

  # source://activestorage/8.0.1/lib/active_storage.rb#63
  def content_types_allowed_inline; end

  # source://activestorage/8.0.1/lib/active_storage.rb#63
  def content_types_allowed_inline=(val); end

  # source://activestorage/8.0.1/lib/active_storage.rb#62
  def content_types_to_serve_as_binary; end

  # source://activestorage/8.0.1/lib/active_storage.rb#62
  def content_types_to_serve_as_binary=(val); end

  # source://activestorage/8.0.1/lib/active_storage.rb#361
  def draw_routes; end

  # source://activestorage/8.0.1/lib/active_storage.rb#361
  def draw_routes=(val); end

  # source://activestorage/8.0.1/lib/active_storage.rb#48
  def logger; end

  # source://activestorage/8.0.1/lib/active_storage.rb#48
  def logger=(val); end

  # source://activestorage/8.0.1/lib/active_storage.rb#57
  def paths; end

  # source://activestorage/8.0.1/lib/active_storage.rb#57
  def paths=(val); end

  # source://activestorage/8.0.1/lib/active_storage.rb#54
  def previewers; end

  # source://activestorage/8.0.1/lib/active_storage.rb#54
  def previewers=(val); end

  # source://activestorage/8.0.1/lib/active_storage.rb#52
  def queues; end

  # source://activestorage/8.0.1/lib/active_storage.rb#52
  def queues=(val); end

  # source://activestorage/8.0.1/lib/active_storage.rb#362
  def resolve_model_to_route; end

  # source://activestorage/8.0.1/lib/active_storage.rb#362
  def resolve_model_to_route=(val); end

  # source://activestorage/8.0.1/lib/active_storage.rb#360
  def routes_prefix; end

  # source://activestorage/8.0.1/lib/active_storage.rb#360
  def routes_prefix=(val); end

  # source://activestorage/8.0.1/lib/active_storage.rb#356
  def service_urls_expire_in; end

  # source://activestorage/8.0.1/lib/active_storage.rb#356
  def service_urls_expire_in=(val); end

  # source://activestorage/8.0.1/lib/active_storage.rb#65
  def supported_image_processing_methods; end

  # source://activestorage/8.0.1/lib/active_storage.rb#65
  def supported_image_processing_methods=(val); end

  # source://activestorage/8.0.1/lib/active_storage.rb#357
  def touch_attachment_records; end

  # source://activestorage/8.0.1/lib/active_storage.rb#357
  def touch_attachment_records=(val); end

  # source://activestorage/8.0.1/lib/active_storage.rb#364
  def track_variants; end

  # source://activestorage/8.0.1/lib/active_storage.rb#364
  def track_variants=(val); end

  # source://activestorage/8.0.1/lib/active_storage.rb#354
  def unsupported_image_processing_arguments; end

  # source://activestorage/8.0.1/lib/active_storage.rb#354
  def unsupported_image_processing_arguments=(val); end

  # source://activestorage/8.0.1/lib/active_storage.rb#358
  def urls_expire_in; end

  # source://activestorage/8.0.1/lib/active_storage.rb#358
  def urls_expire_in=(val); end

  # source://activestorage/8.0.1/lib/active_storage.rb#59
  def variable_content_types; end

  # source://activestorage/8.0.1/lib/active_storage.rb#59
  def variable_content_types=(val); end

  # source://activestorage/8.0.1/lib/active_storage.rb#50
  def variant_processor; end

  # source://activestorage/8.0.1/lib/active_storage.rb#50
  def variant_processor=(val); end

  # source://activestorage/8.0.1/lib/active_storage.rb#49
  def verifier; end

  # source://activestorage/8.0.1/lib/active_storage.rb#49
  def verifier=(val); end

  # source://activestorage/8.0.1/lib/active_storage.rb#366
  def video_preview_arguments; end

  # source://activestorage/8.0.1/lib/active_storage.rb#366
  def video_preview_arguments=(val); end

  # source://activestorage/8.0.1/lib/active_storage.rb#60
  def web_image_content_types; end

  # source://activestorage/8.0.1/lib/active_storage.rb#60
  def web_image_content_types=(val); end

  class << self
    # source://activestorage/8.0.1/lib/active_storage.rb#55
    def analyzers; end

    # source://activestorage/8.0.1/lib/active_storage.rb#55
    def analyzers=(val); end

    # source://activestorage/8.0.1/lib/active_storage.rb#61
    def binary_content_type; end

    # source://activestorage/8.0.1/lib/active_storage.rb#61
    def binary_content_type=(val); end

    # source://activestorage/8.0.1/lib/active_storage.rb#63
    def content_types_allowed_inline; end

    # source://activestorage/8.0.1/lib/active_storage.rb#63
    def content_types_allowed_inline=(val); end

    # source://activestorage/8.0.1/lib/active_storage.rb#62
    def content_types_to_serve_as_binary; end

    # source://activestorage/8.0.1/lib/active_storage.rb#62
    def content_types_to_serve_as_binary=(val); end

    # source://activestorage/8.0.1/lib/active_storage/deprecator.rb#4
    def deprecator; end

    # source://activestorage/8.0.1/lib/active_storage.rb#361
    def draw_routes; end

    # source://activestorage/8.0.1/lib/active_storage.rb#361
    def draw_routes=(val); end

    # source://activestorage/8.0.1/lib/active_storage/gem_version.rb#5
    def gem_version; end

    # source://activestorage/8.0.1/lib/active_storage.rb#48
    def logger; end

    # source://activestorage/8.0.1/lib/active_storage.rb#48
    def logger=(val); end

    # source://activestorage/8.0.1/lib/active_storage.rb#57
    def paths; end

    # source://activestorage/8.0.1/lib/active_storage.rb#57
    def paths=(val); end

    # source://activestorage/8.0.1/lib/active_storage.rb#54
    def previewers; end

    # source://activestorage/8.0.1/lib/active_storage.rb#54
    def previewers=(val); end

    # source://activestorage/8.0.1/lib/active_storage.rb#52
    def queues; end

    # source://activestorage/8.0.1/lib/active_storage.rb#52
    def queues=(val); end

    # source://railties/8.0.1/lib/rails/engine.rb#413
    def railtie_helpers_paths; end

    # source://railties/8.0.1/lib/rails/engine.rb#396
    def railtie_namespace; end

    # source://railties/8.0.1/lib/rails/engine.rb#417
    def railtie_routes_url_helpers(include_path_helpers = T.unsafe(nil)); end

    # source://activestorage/8.0.1/lib/active_storage.rb#362
    def resolve_model_to_route; end

    # source://activestorage/8.0.1/lib/active_storage.rb#362
    def resolve_model_to_route=(val); end

    # source://activestorage/8.0.1/lib/active_storage.rb#360
    def routes_prefix; end

    # source://activestorage/8.0.1/lib/active_storage.rb#360
    def routes_prefix=(val); end

    # source://activestorage/8.0.1/lib/active_storage.rb#356
    def service_urls_expire_in; end

    # source://activestorage/8.0.1/lib/active_storage.rb#356
    def service_urls_expire_in=(val); end

    # source://activestorage/8.0.1/lib/active_storage.rb#65
    def supported_image_processing_methods; end

    # source://activestorage/8.0.1/lib/active_storage.rb#65
    def supported_image_processing_methods=(val); end

    # source://railties/8.0.1/lib/rails/engine.rb#402
    def table_name_prefix; end

    # source://activestorage/8.0.1/lib/active_storage.rb#357
    def touch_attachment_records; end

    # source://activestorage/8.0.1/lib/active_storage.rb#357
    def touch_attachment_records=(val); end

    # source://activestorage/8.0.1/lib/active_storage.rb#364
    def track_variants; end

    # source://activestorage/8.0.1/lib/active_storage.rb#364
    def track_variants=(val); end

    # source://activestorage/8.0.1/lib/active_storage.rb#354
    def unsupported_image_processing_arguments; end

    # source://activestorage/8.0.1/lib/active_storage.rb#354
    def unsupported_image_processing_arguments=(val); end

    # source://activestorage/8.0.1/lib/active_storage.rb#358
    def urls_expire_in; end

    # source://activestorage/8.0.1/lib/active_storage.rb#358
    def urls_expire_in=(val); end

    # source://railties/8.0.1/lib/rails/engine.rb#409
    def use_relative_model_naming?; end

    # source://activestorage/8.0.1/lib/active_storage.rb#59
    def variable_content_types; end

    # source://activestorage/8.0.1/lib/active_storage.rb#59
    def variable_content_types=(val); end

    # source://activestorage/8.0.1/lib/active_storage.rb#50
    def variant_processor; end

    # source://activestorage/8.0.1/lib/active_storage.rb#50
    def variant_processor=(val); end

    # source://activestorage/8.0.1/lib/active_storage.rb#49
    def verifier; end

    # source://activestorage/8.0.1/lib/active_storage.rb#49
    def verifier=(val); end

    # source://activestorage/8.0.1/lib/active_storage/version.rb#7
    def version; end

    # source://activestorage/8.0.1/lib/active_storage.rb#366
    def video_preview_arguments; end

    # source://activestorage/8.0.1/lib/active_storage.rb#366
    def video_preview_arguments=(val); end

    # source://activestorage/8.0.1/lib/active_storage.rb#60
    def web_image_content_types; end

    # source://activestorage/8.0.1/lib/active_storage.rb#60
    def web_image_content_types=(val); end
  end
end

# source://activestorage-validator//lib/activestorage/validator/version.rb#2
module ActiveStorage::Validator; end

# source://activestorage-validator//lib/activestorage/validator/version.rb#3
ActiveStorage::Validator::VERSION = T.let(T.unsafe(nil), String)
