// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FileController from "./file_controller"
application.register("file", FileController)

import ProductSearchController from "./product_search_controller"
application.register("product-search", ProductSearchController)

import TooltipController from "./tooltip_controller"
application.register("tooltip", TooltipController)
