# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `CarouselComponent`.
# Please instead update this file by running `bin/tapioca dsl CarouselComponent`.


class CarouselComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
