# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ListItemComponent`.
# Please instead update this file by running `bin/tapioca dsl ListItemComponent`.


class ListItemComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
