# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ProductCardComponent`.
# Please instead update this file by running `bin/tapioca dsl ProductCardComponent`.


class ProductCardComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
