# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ProductDetailsComponent`.
# Please instead update this file by running `bin/tapioca dsl ProductDetailsComponent`.


class ProductDetailsComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
