# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ProductShowComponent`.
# Please instead update this file by running `bin/tapioca dsl ProductShowComponent`.


class ProductShowComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
