# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ReviewComponent`.
# Please instead update this file by running `bin/tapioca dsl ReviewComponent`.


class ReviewComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
