# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `SearchComponent`.
# Please instead update this file by running `bin/tapioca dsl SearchComponent`.


class SearchComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
