# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `SpacerComponent`.
# Please instead update this file by running `bin/tapioca dsl SpacerComponent`.


class SpacerComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
