# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `StoreCardComponent`.
# Please instead update this file by running `bin/tapioca dsl StoreCardComponent`.


class StoreCardComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
