# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `TooltipComponent`.
# Please instead update this file by running `bin/tapioca dsl TooltipComponent`.


class TooltipComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
